version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"  # Adjust as needed

  fastapi:
    build: ./backend
    container_name: fastapi
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - ollama

  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    depends_on:
      - fastapi
